export const options = [
  "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTC", "BTN", "BWP", "BYN", "BYR", "BZD", "CAD", "CDF", "CHF", "CLF", "CLP", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LTL", "LVL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRO", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "STD", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VEF", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XCD", "XDR", "XOF", "XPF", "YER", "ZAR", "ZMK", "ZMW", "ZWL"
]

export const name = [
  "Emirate Dirham", "Afghan Afghani", "Albanian Lek", "Armenian Dram", "Dutch Guilder", "Angolan Kwanza", "Argentine Peso", "Australian Dollar", "Aruban Guilder", "Azerbaijan Manat", "Bosnian Convertible Mark", "Barbadian Dollar", "Bangladesh Taka", "Bulgarian Lev", "Bahraini Dinar", "Burudian Franc", "Bermudian Dollar", "Bruneian Dollar", "Bolivian Boliviano", "Brazilian Real", "Bahamian Dollar", "BTC", "Bhutanese Ngultrum", "Botswana Pula", "Belarusian Ruble", "Belarusian Ruble (obsolete)", "Belizean Dollar", "Canadian Dollar", "Congolese Franc", "Swiss Franc", "CLF", "Chilean Peso", "Chinese Yuan", "Colombian Peso", "Costa Rican Colan", "Cuban Convertible Peso", "Cuban Peso", "Cabo Verde Escudo", "Czech Koruna", "Djibouti Franc", "Danish Krone", "Dominican Peso", "Algerian Dinar", "Egyptian Pound", "Nakfa", "Ethiopian Birr", "Euro", "Fiji Dollar", "Falkland Islands Pound", "Pound Sterling", "Lari", "GGP", "Ghana Cedi", "Gibraltar Pound", "Dalasi", "Guinea Franc", "Quetzal", "Guyana Dollar", "Hong Kong Dollar", "Lempira", "Kuna", "Gourde", "Forint", "Rupiah", "New Israeli Sheqel", "IMP", "Indian Rupee", "Iraqi Dinar", "Iranian Rial", "Iceland Krona", "JEP", "Jamaican Dollar", "Jordanian Dinar", "Yen", "Kenyan Shilling", "Som", "Riel", "Comoro Franc", "North Korean Won", "Won", "Kuwaiti Dinar", "Cayman Islands Dollar", "Tenge", "Kip", "Lebanese Pound", "Sri Lanka Rupee", "Liberian Dollar", "Loti", "LTL", "LVL", "Libyan Dinar", "Moroccan Dirham", "Moldovan Leu", "Malagasy Ariary", "Denar", "Kyat", "Tugrik", "Pataca", "MRO", "Mauritius Rupee", "Rufiyaa", "Kwacha", "Mexican Peso", "Malaysian Ringgit", "Mozambique Metical", "Namibia Dollar", "Naira", "Cordoba Oro", "Norwegian Krone", "Nepalese Rupee", "New Zealand Dollar", "Rial Omani", "Balboa", "Nuevo Sol", "Kina", "Philippine Peso", "Pakistan Rupee", "Zloty", "Guarani", "Qatari Rial", "Romanian Leu", "Serbian Dinar", "Russian Ruble", "Rwanda Franc", "Saudi Riyal", "Solomon Islands Dollar", "Seychelles Rupee", "Sudanese Pound", "Swedish Krona", "Singapore Dollar", "Saint Helena Pound", "Leone", "Somali Shilling", "Surinam Dollar", "STD", "El Salvador Colon", "Syrian Pound", "Lilangeni", "Baht", "Somoni", "Turkmenistan New Manat", "Tunisian Dinar", "Pa’anga", "Turkish Lira", "Trinidad and Tobago Dollar", "New Taiwan Dollar", "Tanzanian Shilling", "Hryvnia", "Uganda Shilling", "US Dollar", "Peso Uruguayo", "Uzbekistan Sum", "Bolivar", "Dong", "Vatu", "Tala", "Central African Franc", "Silver Ounce", "Gold Ounce", "Easy Caribbean Dollar", "IMF Special Drawing Rights", "CFA Franc", "CFP Franc", "Yemeni Rial", "South African Rand", "Zambian Kwacha(obsolete)", "Zambian Kwacha", "Zimbabwe Dollar"
]

export const xValues = [
  { key: "AED", name: "Emirate Dirham" },
  { key: "AFN", name: "Afghan Afghani" },
  { key: "ALL", name: "Albanian Lek" },
  { key: "AMD", name: "Armenian Dram" },
  { key: "ANG", name: "Dutch Guilder" },
  { key: "AOA", name: "Angolan Kwanza" },
  { key: "ARS", name: "Argentine Peso" },
  { key: "AUD", name: "Australian Dollar" },
  { key: "AWG", name: "Aruban Guilder" },
  { key: "AZN", name: "Azerbaijan Manat" },
  { key: "BAM", name: "Bosnian Convertible Mark" },
  { key: "BBD", name: "Barbadian Dollar" },
  { key: "BDT", name: "Bangladesh Taka" },
  { key: "BGN", name: "Bulgarian Lev" },
  { key: "BHD", name: "Bahraini Dinar" },
  { key: "BIF", name: "Burudian Franc" },
  { key: "BMD", name: "Bermudian Dollar" },
  { key: "BND", name: "Bruneian Dollar" },
  { key: "BOB", name: "Bolivian Boliviano" },
  { key: "BRL", name: "Brazilian Real" },
  { key: "BSD", name: "Bahamian Dollar" },
  { key: "BTC", name: "BTC" },
  { key: "BTN", name: "Bhutanese Ngultrum" },
  { key: "BWP", name: "Botswana Pula" },
  { key: "BYN", name: "Belarusian Ruble" },
  { key: "BYR", name: "Belarusian Ruble (obsolete)" },
  { key: "BZD", name: "Belizean Dollar" },
  { key: "CAD", name: "Canadian Dollar" },
  { key: "CDF", name: "Congolese Franc" },
  { key: "CHF", name: "Swiss Franc" },
  { key: "CLF", name: "CLF" },
  { key: "CLP", name: "Chilean Peso" },
  { key: "CNY", name: "Chinese Yuan" },
  { key: "COP", name: "Colombian Peso" },
  { key: "CRC", name: "Costa Rican Colan" },
  { key: "CUC", name: "Cuban Convertible Peso" },
  { key: "CUP", name: "Cuban Peso" },
  { key: "CVE", name: "Cabo Verde Escudo" },
  { key: "CZK", name: "Czech Koruna" },
  { key: "DJF", name: "Djibouti Franc" },
  { key: "DKK", name: "Danish Krone" },
  { key: "DOP", name: "Dominican Peso" },
  { key: "DZD", name: "Algerian Dinar" },
  { key: "EGP", name: "Egyptian Pound" },
  { key: "ERN", name: "Nakfa" },
  { key: "ETB", name: "Ethiopian Birr" },
  { key: "EUR", name: "Euro" },
  { key: "FJD", name: "Fiji Dollar" },
  { key: "FKP", name: "Falkland Islands Pound" },
  { key: "GBP", name: "Pound Sterling" },
  { key: "GEL", name: "Lari" },
  { key: "GGP", name: "GGP" },
  { key: "GHS", name: "Ghana Cedi" },
  { key: "GIP", name: "Gibraltar Pound" },
  { key: "GMD", name: "Dalasi" },
  { key: "GNF", name: "Guinea Franc" },
  { key: "GTQ", name: "Quetzal" },
  { key: "GYD", name: "Guyana Dollar" },
  { key: "HKD", name: "Hong Kong Dollar" },
  { key: "HNL", name: "Lempira" },
  { key: "HRK", name: "Kuna" },
  { key: "HTG", name: "Gourde" },
  { key: "HUF", name: "Forint" },
  { key: "IDR", name: "Rupiah" },
  { key: "ILS", name: "New Israeli Sheqel" },
  { key: "IMP", name: "IMP" },
  { key: "INR", name: "Indian Rupee" },
  { key: "IQD", name: "Iraqi Dinar" },
  { key: "IRR", name: "Iranian Rial" },
  { key: "ISK", name: "Iceland Krona" },
  { key: "JEP", name: "JEP" },
  { key: "JMD", name: "Jamaican Dollar" },
  { key: "JOD", name: "Jordanian Dinar" },
  { key: "JPY", name: "Yen" },
  { key: "KES", name: "Kenyan Shilling" },
  { key: "KGS", name: "Som" },
  { key: "KHR", name: "Riel" },
  { key: "KMF", name: "Comoro Franc" },
  { key: "KPW", name: "North Korean Won" },
  { key: "KRW", name: "Won" },
  { key: "KWD", name: "Kuwaiti Dinar" },
  { key: "KYD", name: "Cayman Islands Dollar" },
  { key: "KZT", name: "Tenge" },
  { key: "LAK", name: "Kip" },
  { key: "LBP", name: "Lebanese Pound" },
  { key: "LKR", name: "Sri Lanka Rupee" },
  { key: "LRD", name: "Liberian Dollar" },
  { key: "LSL", name: "Loti" },
  { key: "LTL", name: "LTL" },
  { key: "LVL", name: "LVL" },
  { key: "LYD", name: "Libyan Dinar" },
  { key: "MAD", name: "Moroccan Dirham" },
  { key: "MDL", name: "Moldovan Leu" },
  { key: "MGA", name: "Malagasy Ariary" },
  { key: "MKD", name: "Denar" },
  { key: "MMK", name: "Kyat" },
  { key: "MNT", name: "Tugrik" },
  { key: "MOP", name: "Pataca" },
  { key: "MRO", name: "MRO" },
  { key: "MUR", name: "Mauritius Rupee" },
  { key: "MVR", name: "Rufiyaa" },
  { key: "MWK", name: "Kwacha" },
  { key: "MXN", name: "Mexican Peso" },
  { key: "MYR", name: "Malaysian Ringgit" },
  { key: "MZN", name: "Mozambique Metical" },
  { key: "NAD", name: "Namibia Dollar" },
  { key: "NGN", name: "Naira" },
  { key: "NIO", name: "Cordoba Oro" },
  { key: "NOK", name: "Norwegian Krone" },
  { key: "NPR", name: "Nepalese Rupee" },
  { key: "NZD", name: "New Zealand Dollar" },
  { key: "OMR", name: "Rial Omani" },
  { key: "PAB", name: "Balboa" },
  { key: "PEN", name: "Nuevo Sol" },
  { key: "PGK", name: "Kina" },
  { key: "PHP", name: "Philippine Peso" },
  { key: "PKR", name: "Pakistan Rupee" },
  { key: "PLN", name: "Zloty" },
  { key: "PYG", name: "Guarani" },
  { key: "QAR", name: "Qatari Rial" },
  { key: "RON", name: "Romanian Leu" },
  { key: "RSD", name: "Serbian Dinar" },
  { key: "RUB", name: "Russian Ruble" },
  { key: "RWF", name: "Rwanda Franc" },
  { key: "SAR", name: "Saudi Riyal" },
  { key: "SBD", name: "Solomon Islands Dollar" },
  { key: "SCR", name: "Seychelles Rupee" },
  { key: "SDG", name: "Sudanese Pound" },
  { key: "SEK", name: "Swedish Krona" },
  { key: "SGD", name: "Singapore Dollar" },
  { key: "SHP", name: "Saint Helena Pound" },
  { key: "SLL", name: "Leone" },
  { key: "SOS", name: "Somali Shilling" },
  { key: "SRD", name: "Surinam Dollar" },
  { key: "STD", name: "STD" },
  { key: "SVC", name: "El Salvador Colon" },
  { key: "SYP", name: "Syrian Pound" },
  { key: "SZL", name: "Lilangeni" },
  { key: "THB", name: "Baht" },
  { key: "TJS", name: "Somoni" },
  { key: "TMT", name: "Turkmenistan New Manat" },
  { key: "TND", name: "Tunisian Dinar" },
  { key: "TOP", name: "Pa’anga" },
  { key: "TRY", name: "Turkish Lira" },
  { key: "TTD", name: "Trinidad and Tobago Dollar" },
  { key: "TWD", name: "New Taiwan Dollar" },
  { key: "TZS", name: "Tanzanian Shilling" },
  { key: "UAH", name: "Hryvnia" },
  { key: "UGX", name: "Uganda Shilling" },
  { key: "USD", name: "US Dollar" },
  { key: "UYU", name: "Peso Uruguayo" },
  { key: "UZS", name: "Uzbekistan Sum" },
  { key: "VEF", name: "Bolivar" },
  { key: "VND", name: "Dong" },
  { key: "VUV", name: "Vatu" },
  { key: "WST", name: "Tala" },
  { key: "XAF", name: "Central African Franc" },
  { key: "XAG", name: "Silver Ounce" },
  { key: "XAU", name: "Gold Ounce" },
  { key: "XCD", name: "Easy Caribbean Dollar" },
  { key: "XDR", name: "IMF Special Drawing Rights" },
  { key: "XOF", name: "CFA Franc" },
  { key: "XPF", name: "CFP Franc" },
  { key: "YER", name: "Yemeni Rial" },
  { key: "ZAR", name: "South African Rand" },
  { key: "ZMK", name: "Zambian Kwacha(obsolete)" },
  { key: "ZMW", name: "Zambian Kwacha" },
  { key: "ZWL", name: "Zimbabwe Dollar" }
]